apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
data:
  APP_ENV: "production"
  SERVICE_NAME: "order-service"
  DATABASE_URL: "postgresql://$DATABASE_USER:$DATABASE_PASSWORD@order-service-postgres-rw.order-service.svc.cluster.local:5432/order-service"
